@startuml
'https://plantuml.com/class-diagram

package VRShooting
{
    package Player
    {
        class PlayerEquippedGunSwitcher
        {
            -[SerializedField] GunVariant _initialGun
            -[SerializedField] List<GunVariant> _equipGunMap
            -Dictionary<GunVariant, IGun> _gunStrategyData
            -IPlayerGunHandler _gunHandler
            -void Start()
            -void InitializedStrategyData()
            +void AddGun(GunVariant gunName, IGun gunInstance)
        }
        interface IPlayerEquippedGunSwitcher
        {
            +void AddGun(GunVariant gunName, IGun gunInstance)
        }
        
        PlayerEquippedGunSwitcher ..|> IPlayerEquippedGunSwitcher
    }
}
@enduml