@startuml
'https://plantuml.com/class-diagram

package Enemy
{
    class EnemyMovement
    {
        -IEnemyStateController _enemyStateController
        +void Move()
        -void Start()
    }
    interface IEnemyMovement
    {
        +void Move()
    }
    EnemyMovement ..|> IEnemyMovement
}
@enduml