@startuml
'https://plantuml.com/class-diagram

package Enemy
{
    class EnemyObject
    {
        +void SpawnInitialize()
    }
    
    interface IEnemyObject
    {
        +void SpawnInitialize()
    }
    
    EnemyObject ..u|> IEnemyObject
}

@enduml