@startuml
'https://plantuml.com/class-diagram

package Enemy
{
    class EnemyStateController
    {
        +event Action OnEnterIdle
        +event Action OnExitIdle
        +event Action<float> OnUpdateIdle
        +event Action OnEnterMove
        +event Action OnExitMove
        +event Action<float> OnUpdateMove
        +event Action OnEnterDead
        +event Action OnExitDead
        +event Action<float> OnUpdateDead
        +StateMachine<EnemyState, EnemyStateTrigger> enemyStateMachine => _enemyStateMachine
        -StateMachine<EnemyState, EnemyStateTrigger> _enemyStateMachine
    }
    interface IEnemyStateController
    {
        +event Action OnEnterIdle
        +event Action OnExitIdle
        +event Action<float> OnUpdateIdle
        +event Action OnEnterMove
        +event Action OnExitMove
        +event Action<float> OnUpdateMove
        +event Action OnEnterDead
        +event Action OnExitDead
        +event Action<float> OnUpdateDead
        +StateMachine<EnemyState, EnemyStateTrigger> enemyStateMachine { get; }
    }
    
    EnemyStateController ..|> IEnemyStateController
}
@enduml