@startuml
'https://plantuml.com/class-diagram

package VRShooting
{
    package Gun
    {
        enum BulletState
        {
            Normal
            Reflection
        }
        class Bullet
        {
            -IBulletData bulletData
            -BulletState _bulletState
            -Vector3 _moveDirection
            +void Spawn(Transform spawnPosition, Vector3 moveDirection, ref ObjectPool<IBullet> objectPool)
            -void Start()
            -void Update()
            -void OnTriggerEnter(Collider other)
        }
        interface IBullet
        {
            +void Spawn(Transform spawnPosition)
        }
        Bullet ..|> IBullet
    }
}

@enduml