@startuml
'https://plantuml.com/class-diagram

package VRShooting
{
    package Gun
    {
        class GunData
        {
            +IBullet bulletObj => _bulletObj
            -[SerializedField] Bullet _bulletObj
            +float fireRate => _fireRate
            -[SerializedField] float _fireRate
            etc..
            +void ChangeFireRate(float fireRate)
            etc..()
        }
        interface IGunData
        {
            +IBullet bulletObj => _bulletObj
            +float fireRate => _fireRate
            etc..
            +void ChangeFireRate(float fireRate)
            etc..()
        }
        
        GunData ..|> IGunData
    }
}

@enduml