@startuml
'https://plantuml.com/class-diagram

package VRShooting
{
    package Gun
    {
        class GunObject
        {
            -[SerializedField] Transform _muzzle
            -ObjectPool<IBullet> _bulletPool
            -IGunData _gunData
            +void Shoot()
            +void Equipped(Transform handPosition)
            +void RemoveEquipment()
            -void Start()
            -void CreateBulletObjectPool()
            -void ReleaseBulletObjectPool()
        }
        interface IGun
        {
            +void Shoot()
            +void Equipped(Transform handPosition)
            +void RemoveEquipment()
        }
        
        GunObject ..|> IGun
    }
}

@enduml